image: haskell:8.0.2

build:
  stage: build
  script:
    - cabal update
      && cabal install mtl-2.2.1
      && cabal install pretty-tree
      && cabal install quickspec
      && cabal install concurrent-extra
      && ghc -O2 Recipe/Main.hs
      && ./Recipe/Main