image: haskell:8.2.1

build:
  stage: build
  script:
    - cabal update
      && cabal install mtl-2.2.1
      && cabal install pretty-tree
      && cabal install quickspec
      && cabal install concurrency-extra
      && ghc -O2 Recipe.Demo