name:                recipeDSL
version:             0.1.0.0
github:              "githubuser/recipeDSL"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 James Burton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/recipeDSL#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- pretty-tree
- containers
- concurrent-extra
- random
- unbounded-delays
- mtl
- QuickCheck
- quickspec

library:
  source-dirs: src

# executables:
#   recipeDSL-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - recipeDSL

tests:
  recipeDSL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recipeDSL
